project:
  type: website
  output-dir: docs

website:
  title: "Bianca Brusco"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - teaching.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: visual

